### ISSUE TITLE
Concurrent Modification in `postOpen` method

### ISSUE THREAD

**Issue by luiz-otavio** [DevNatan/inventory-framework#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

When I try to open a view, a throwable is called as `ConcurrentModificationExpection`.

```
java.util.ConcurrentModificationException: null
        at java.util.ArrayList.forEach(ArrayList.java:1513) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractView.postOpen(AbstractView.java:288) ~[bukkit-1.0.8-dev-all.jar:?]
        at me.saiintbrisson.minecraft.AbstractView.open(AbstractView.java:260) ~[bukkit-1.0.8-dev-all.jar:?]
        at me.saiintbrisson.minecraft.ViewFrame.lambda$open$0(ViewFrame.java:226) ~[bukkit-1.0.8-dev-all.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1580) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:502) ~[patched_1.17.1.jar:git-Airplane-"7a3ca1d"]
```

### ✔️ Expected behavior

Just giving no output about that stracktrace.

### 👣 Steps to Reproduce

1. Make a view;
2. Override `onRender` method;
3. Call  `open(View)`. 

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Version

1.17.1

**Comment by DevNatan** [comment]
@luiz-otavio Fixed in [v2.5.1](https://github.com/DevNatan/inventory-framework/releases/tag/2.5.1) please try the new version!

**Comment by Azodox** [comment]
Hi, @DevNatan I'm still having the same issue in version 2.5.3

```
java.util.ConcurrentModificationException
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_341]
        at java.util.Collections$UnmodifiableCollection.forEach(Unknown Source) ~[?:1.8.0_341]
        at me.saiintbrisson.minecraft.AbstractView.postOpen(AbstractView.java:282) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractView.open(AbstractView.java:260) ~[?:?]
        at me.saiintbrisson.minecraft.ViewFrame.lambda$open$0(ViewFrame.java:227) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
```

**Comment by DevNatan** [comment]
> Hi, @DevNatan I'm still having the same issue in version 2.5.3
> 
> ```
> java.util.ConcurrentModificationException
>         at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_341]
>         at java.util.Collections$UnmodifiableCollection.forEach(Unknown Source) ~[?:1.8.0_341]
>         at me.saiintbrisson.minecraft.AbstractView.postOpen(AbstractView.java:282) ~[?:?]
>         at me.saiintbrisson.minecraft.AbstractView.open(AbstractView.java:260) ~[?:?]
>         at me.saiintbrisson.minecraft.ViewFrame.lambda$open$0(ViewFrame.java:227) ~[?:?]
>         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
> ```

ya, i noticed that in the [last tests](https://github.com/DevNatan/inventory-framework/pull/199) i did, it is expected to be fixed in the next version, sorry for the same bug again

**Comment by Azodox** [comment]
thx, no problem

**Comment by DevNatan** [comment]
@Azodox A lot of things have changed since this bug occurred, I released [v2.5.4-beta](https://github.com/DevNatan/inventory-framework/releases/tag/2.5.4-beta) which moved the opening process to an pipeline interceptor so it changed a lot, I will keep the issue open, if this happens with you again you can report here

**Comment by Azodox** [comment]
Alright, huge thanks to you @DevNatan and what you do. Always a great support :)

**Comment by Azodox** [comment]
@DevNatan Ahaha I think there is another problem when you have a scheduled update, or may I missed something with the new version?

```
java.lang.IllegalStateException: Update job not started to be resumed
        at me.saiintbrisson.minecraft.BukkitViewUpdateJobImpl.resume(BukkitViewUpdateJobImpl.java:60) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.interceptors.ScheduledUpdateInterceptor$Render.intercept(ScheduledUpdateInterceptor.java:34) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.interceptors.ScheduledUpdateInterceptor$Render.intercept(ScheduledUpdateInterceptor.java:24) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.PipelineContext.loop(PipelineContext.java:39) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.PipelineContext.proceed(PipelineContext.java:49) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.PipelineContext.execute(PipelineContext.java:55) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.Pipeline.execute(Pipeline.java:117) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractView.lambda$render$0(AbstractView.java:279) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractVirtualView.runCatching(AbstractVirtualView.java:383) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractView.render(AbstractView.java:277) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.interceptors.OpenInterceptor.finishOpen(OpenInterceptor.java:72) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.interceptors.OpenInterceptor.intercept(OpenInterceptor.java:30) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.interceptors.OpenInterceptor.intercept(OpenInterceptor.java:19) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.PipelineContext.loop(PipelineContext.java:39) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.PipelineContext.proceed(PipelineContext.java:49) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.PipelineContext.execute(PipelineContext.java:55) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.Pipeline.execute(Pipeline.java:117) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractView.open(AbstractView.java:270) ~[?:?]
        at me.saiintbrisson.minecraft.ViewFrame.lambda$open$0(ViewFrame.java:245) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
```

**Comment by DevNatan** [comment]
> @DevNatan Ahaha I think there is another problem when you have a scheduled update, or may I missed something with the new version?
> 
> ```
> java.lang.IllegalStateException: Update job not started to be resumed
>         at me.saiintbrisson.minecraft.BukkitViewUpdateJobImpl.resume(BukkitViewUpdateJobImpl.java:60) ~[?:?]
>         at me.saiintbrisson.minecraft.pipeline.interceptors.ScheduledUpdateInterceptor$Render.intercept(ScheduledUpdateInterceptor.java:34) ~[?:?]
>         at me.saiintbrisson.minecraft.pipeline.interceptors.ScheduledUpdateInterceptor$Render.intercept(ScheduledUpdateInterceptor.java:24) ~[?:?]
>         at me.saiintbrisson.minecraft.pipeline.PipelineContext.loop(PipelineContext.java:39) ~[?:?]
>         at me.saiintbrisson.minecraft.pipeline.PipelineContext.proceed(PipelineContext.java:49) ~[?:?]
>         at me.saiintbrisson.minecraft.pipeline.PipelineContext.execute(PipelineContext.java:55) ~[?:?]
>         at me.saiintbrisson.minecraft.pipeline.Pipeline.execute(Pipeline.java:117) ~[?:?]
>         at me.saiintbrisson.minecraft.AbstractView.lambda$render$0(AbstractView.java:279) ~[?:?]
>         at me.saiintbrisson.minecraft.AbstractVirtualView.runCatching(AbstractVirtualView.java:383) ~[?:?]
>         at me.saiintbrisson.minecraft.AbstractView.render(AbstractView.java:277) ~[?:?]
>         at me.saiintbrisson.minecraft.pipeline.interceptors.OpenInterceptor.finishOpen(OpenInterceptor.java:72) ~[?:?]
>         at me.saiintbrisson.minecraft.pipeline.interceptors.OpenInterceptor.intercept(OpenInterceptor.java:30) ~[?:?]
>         at me.saiintbrisson.minecraft.pipeline.interceptors.OpenInterceptor.intercept(OpenInterceptor.java:19) ~[?:?]
>         at me.saiintbrisson.minecraft.pipeline.PipelineContext.loop(PipelineContext.java:39) ~[?:?]
>         at me.saiintbrisson.minecraft.pipeline.PipelineContext.proceed(PipelineContext.java:49) ~[?:?]
>         at me.saiintbrisson.minecraft.pipeline.PipelineContext.execute(PipelineContext.java:55) ~[?:?]
>         at me.saiintbrisson.minecraft.pipeline.Pipeline.execute(Pipeline.java:117) ~[?:?]
>         at me.saiintbrisson.minecraft.AbstractView.open(AbstractView.java:270) ~[?:?]
>         at me.saiintbrisson.minecraft.ViewFrame.lambda$open$0(ViewFrame.java:245) ~[?:?]
>         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
> ```

@Azodox any reproducible code? i'll createan issue

**Comment by Azodox** [comment]
> @Azodox any reproducible code? i'll createan issue

```kotlin
class SettingsView(private val uhc: UHC) : View(9 * 6, "§cParamètres") {

    init {
        isCancelOnClick = true
        isCancelOnClone = true
        isCancelOnDrag = true
        isCancelOnDrop = true
        isCancelOnPickup = true
        isCancelOnMoveOut = true
        isCancelOnShiftClick = true

        slot(0, ItemStack(Material.BOOK_AND_QUILL)).onClick {
            it.open(SettingsView::class.java)
        }

        slot(1, ItemStack(Material.FEATHER)).onRender {
            it.setItem(ItemBuilder(Material.FEATHER).displayName("§e${uhc.gameConfiguration.preLoad}").build())
        }.onClick {
            uhc.gameConfiguration.preLoad = !uhc.gameConfiguration.preLoad
            it.update()
        }

        scheduleUpdate(20)
    }
}
```
Oh, by the way, I'm in Kotlin but I guess you can still deal with it :)
